source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target ‘PruebaBeRepublic’ do
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'
    pod 'ObjectMapper', '~> 2.2'
    pod 'AlamofireObjectMapper', '~> 4.0'
end
